# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'

default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_DATABASE'] %>

development:
  <<: *default

production:
  <<: *default
